# This environment.yml is only provided for local development/testing. It plays no role in deployment.
name: galaxy-tool-structural-validator
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - hmmer=3.3.2
  - pip:
    - planemo
    - barcode-validator==2.0.0
    - nbitk